eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 10.78.115.171
    port: 5672
    username: guest
    password: guest
  redis:
    host: 10.78.115.171
    port: 6379
env: test4
girl:
  name: canyou
  age: 16
